### ISSUE TITLE
syntax highlight bug

### ISSUE THREAD

**Issue by laoshaw** [kylelaker/riscv.vim#7]
Where ever there is a ' in the comment all text after that is highlighted. see the screenshot

![image](https://user-images.githubusercontent.com/18351761/165983326-ace0e705-9539-4c9d-82e2-8cfc147c8c82.png)

**Comment by laoshaw** [comment]
I commented out line 17 from syntax/riscv.vim to work around it, I'm sure there is a better/proper fix

**Comment by laurelmay** [comment]
Hey @laoshaw! This should be fixed now in 3259f230a67cb0114b235815a668c8b210cd2b18. Can you update your plugin and confirm? `//` is now a supported comment type!

![image](https://user-images.githubusercontent.com/850893/165990277-9178f699-30da-4342-96ab-88128c7ffed3.png)

**Comment by laoshaw** [comment]
yes `//` works now, still, `/* my comment has' highlights the rest behind */`

**Comment by laurelmay** [comment]
ahh yeah, `/*` comments may not be supported... okay let me try to work that out

**Comment by laurelmay** [comment]
Okay! Multiline comments should now work in 76b8e8a99d9d96e5c7c97c2b1e654ca50d539986!

![image](https://user-images.githubusercontent.com/850893/165995953-76398381-0f7b-4f36-9e81-d6ea4edb5016.png)

**Comment by laoshaw** [comment]
Thanks! :)
