### ISSUE TITLE
vtcvt -> vfcvt Typo

### ISSUE THREAD

**Issue by mkreddy007** [kylelaker/riscv.vim#9]
-syntax keyword riscvInstruction vfcvt.rtz.xu.f.v vtcvt.rtz.x.f.v
+syntax keyword riscvInstruction vfcvt.rtz.xu.f.v vfcvt.rtz.x.f.v

vtcvt should be vfcvt.

**Comment by laurelmay** [comment]
Closed by #10. Thanks again!
